package no.nav.k9.domene.modell

enum class EventResultat {
    LUKK_OPPGAVE,
    LUKK_OPPGAVE_VENT,
    LUKK_OPPGAVE_MANUELT_VENT,
    GJENÅPNE_OPPGAVE,
    OPPRETT_BESLUTTER_OPPGAVE,
    OPPRETT_PAPIRSØKNAD_OPPGAVE,
    OPPRETT_OPPGAVE
}
