package no.nav.k9.integrasjon.kafka.dto


enum class EventHendelse {
    AKSJONSPUNKT_OPPRETTET,
    AKSJONSPUNKT_UTFØRT,
    AKSJONSPUNKT_TILBAKEFØR,
    AKSJONSPUNKT_AVBRUTT,
    AKSJONSPUNKT_HAR_ENDRET_BEHANDLENDE_ENHET,
    BEHANDLINGSKONTROLL_EVENT
}
